### ISSUE TITLE
Login functionality

### ISSUE THREAD

**Issue by hyperwebapps** [gui-fkb/twitch-accounts#2]
Hi man, I know it's not an issue, but since there's not the option for discussion, I would like to ask you if it's possible to add login functionality, because at the moment I'm having some problems with another script but in python for login in the accounts because of the integrity token. If you can add the login, I can convert the code from go to python myself. 

Thanks a lot in advance.

**Comment by gui-fkb** [comment]
Hey! just to confirm, do you really need to perform the login functionality? Usually you don't need that, because as you create an account you automatically log in and receive an oauth token, you can just set this auth token into your cookies to stay logged in again, this way performing a new login request it's not necessary.

**Comment by hyperwebapps** [comment]
Thanks man, for the reply. Actually I want to use part of your script for something else, actually I don't want to create the account since I can get them already. I need only the login, because I wanna understand how can I generate the oauth token, to then perform the operations I need. If possible.
