### ISSUE TITLE
Issue creating accounts with and without proxy, kasada issues.

### ISSUE THREAD

**Issue by Jxuser9875321** [gui-fkb/twitch-accounts#4]
**I tried with proxy:** 
https://###.###.###:#### - Using this didnt work (What format must my proxy be in config.go? i did this in the config.go file: Proxy:  "ip:port",       )

**And without proxy:**
I am getting this error:
**_kasada task took too long to resolve_**

Yes I am using the proper API key.
I tried fixing it myself but couldn't get it to work.

here is a screen shot:
![1](https://github.com/user-attachments/assets/883efe8c-3108-4c88-9038-38f028756a8a)

**Comment by gui-fkb** [comment]
Hey, thanks to bringing this up. 

Yeah, the project wasn't working for almost two months due to a few breaking changes, however i've recently made adjustments to address these problems.

The issue with 'kasada task took too long to resolve' was caused by a mismatch in the API configuration. I’ve updated the getTaskResult function to ensure the api_key is properly used.

Also, twitch has recently updated their account creation flow, which also caused issues, but i've adjusted the script to align the new requirements

About the proxy format, it should look like this inside the config.go file -> Proxy: "http://username:password@hostname:port"

Please update to the latest version and try again. If you still encounter issues, feel free to let me know
